# Generated by Django 5.1.6 on 2025-03-12 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_ingreso_monto_mensual_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
