# Generated by Django 5.2 on 2025-04-06 19:02

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_ingreso_monto_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='pago_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[finanzas.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[finanzas.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[finanzas.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[finanzas.models.validate_positive]),
        ),
    ]
