# Generated by Django 5.2 on 2025-04-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_deuda_pago_mensual_alter_deuda_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipogasto'),
        ),
    ]
